name: Build options.json

on:
  push:
    branches:
      - main
  schedule:
    - cron: "38 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout home-manager
        uses: actions/checkout@v4
        with:
          repository: nix-community/home-manager
          ref: refs/heads/master
          path: home-manager
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      - name: Build home-manager options.json
        run: |
          mkdir -p site/home-manager
          git -C home-manager rev-parse HEAD > site/home-manager/revision
          nix-build ./home-manager/default.nix -I nixpkgs=channel:nixpkgs-unstable -I home-manager=home-manager -A docs.json
          cp result/share/doc/home-manager/options.json{,.br} site/home-manager/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
