name: Build options.json

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"
  schedule:
    - cron: "38 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nix-darwin
        uses: actions/checkout@v4
        with:
          repository: LnL7/nix-darwin
          ref: refs/heads/master
          path: nix-darwin
      - name: Checkout home-manager
        uses: actions/checkout@v4
        with:
          repository: nix-community/home-manager
          ref: refs/heads/master
          path: home-manager
      - name: Checkout brakenium/nix-options-json-wrapper
        uses: actions/checkout@v4
        with:
          repository: brakenium/nix-options-json-wrapper
          ref: refs/heads/main
          path: nix-options-json-wrapper
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build darwin options.json
        run: |
          mkdir -p site/darwin
          git -C nix-darwin rev-parse HEAD > site/darwin/revision
          nix-build ./nix-darwin/release.nix -I nixpkgs=channel:nixpkgs-unstable -I darwin=nix-darwin -A docs.optionsJSON
          cp result/share/doc/darwin/options.json{,.br} site/darwin/
      - name: Build home-manager options.json
        run: |
          mkdir -p site/home-manager
          git -C home-manager rev-parse HEAD > site/home-manager/revision
          nix-build ./home-manager/default.nix -I nixpkgs=channel:nixpkgs-unstable -I home-manager=home-manager -A docs.json
          cp result/share/doc/home-manager/options.json{,.br} site/home-manager/
      - name: Build stylix options.json
        run: |
          mkdir -p site/stylix
          nix flake metadata --json ./nix-options-json-wrapper# | jq -r '.locks.nodes.stylix.locked.rev' > site/stylix/revision
          # Use the nix-options-json-wrapper flake to build the options.json for stylix
          nix build ./nix-options-json-wrapper#hmOptionsJSON -I nixpkgs=channel:nixpkgs-unstable
          cp result/share/doc/stylix/options.json{,.br} site/stylix/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
